import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ArticleService {

  art = [
    {
      id:0,
      im1 : "assets/img/article/homme/img-3.jpg",
      im2 : "assets/img/article/homme/img-4.jpg",
      nom : "t-shirt",
      prix: "54",
      qt  : 2,
      oldPrice :"100",
      date : "20/02/2021"
    },
    {
      id:1,
      im1 : "assets/img/article/homme/img-7.jpg",
      im2 : "assets/img/article/homme/img-8.jpg",
      nom : "blazer",
      prix: "99",
      qt  : 15,
      oldPrice : "500" ,
    },
    {
      id:2,
      im1 : "assets/img/article/homme/img-11.jpg",
      im2 : "assets/img/article/homme/img-12.jpg",
      nom : "serwal",
      prix: "120",
      qt  : 6,
      oldPrice : "120" ,
    },
    {
      id:3,
      im1 : "assets/img/article/homme/img-15.jpg",
      im2 : "assets/img/article/homme/img-16.jpg",
      nom : "barnous",
      prix: "504",
      qt  : 10,
      oldPrice : "504",
    },
    {
      id:4,
      im1 : "assets/img/article/homme/img-11.jpg",
      im2 : "assets/img/article/homme/img-12.jpg",
      nom : "serwal",
      prix: "120",
      qt  : 6,
      oldPrice : "120" ,
    },
    {
      id:5,
      im1 : "assets/img/article/homme/img-15.jpg",
      im2 : "assets/img/article/homme/img-16.jpg",
      nom : "barnous",
      prix: "504",
      qt  : 10,
      oldPrice : "504",
    },

    {
      id:6,
      im1 : "assets/img/article/homme/img-15.jpg",
      im2 : "assets/img/article/homme/img-16.jpg",
      nom : "barnous",
      prix: "504",
      qt  : 10,
      oldPrice : "504",
    },
    {
      id  :7,
      im1 : "assets/img/article/homme/img-11.jpg",
      im2 : "assets/img/article/homme/img-12.jpg",
      nom : "serwal",
      prix: "120",
      qt  : 6,
      oldPrice : "120" ,
    },
    {
      id:8,
      im1 : "assets/img/article/homme/img-15.jpg",
      im2 : "assets/img/article/homme/img-16.jpg",
      nom : "barnous",
      prix: "504",
      qt  : 10,
      oldPrice : "504",
    },
    {
      id:9,
      im1 : "assets/img/article/homme/img-3.jpg",
      im2 : "assets/img/article/homme/img-4.jpg",
      nom : "t-shirt",
      prix: "54",
      qt  : 2,
      oldPrice :"100",
    },
    {
      id:10,
      im1 : "assets/img/article/homme/img-7.jpg",
      im2 : "assets/img/article/homme/img-8.jpg",
      nom : "blazer",
      prix: "99",
      qt  : 15,
      oldPrice : "500" ,
    },
    {
      id:10,
      im1 : "assets/img/article/homme/img-11.jpg",
      im2 : "assets/img/article/homme/img-12.jpg",
      nom : "serwal",
      prix: "120",
      qt  : 6,
      oldPrice : "120" ,
    },
    {
      id:11,
      im1 : "assets/img/article/homme/img-15.jpg",
      im2 : "assets/img/article/homme/img-16.jpg",
      nom : "barnous",
      prix: "504",
      qt  : 10,
      oldPrice : "504",
    },
    {
      id  :11,
      im1 : "assets/img/article/homme/img-11.jpg",
      im2 : "assets/img/article/homme/img-12.jpg",
      nom : "serwal",
      prix: "120",
      qt  : 6,
      oldPrice : "120" ,
    },
    {
      id:12,
      im1 : "assets/img/article/homme/img-15.jpg",
      im2 : "assets/img/article/homme/img-16.jpg",
      nom : "barnous",
      prix: "504",
      qt  : 10,
      oldPrice : "504",
    },
    {
      id:13,
      im1 : "assets/img/article/homme/img-3.jpg",
      im2 : "assets/img/article/homme/img-4.jpg",
      nom : "t-shirt",
      prix: "54",
      qt  : 2,
      oldPrice :"100",
    },
  ];
  constructor() { }
}
